# Configuration replicating accuracy experiments from table 2
# training
num_rounds: 1_000
num_clients_per_round: 5
learning_rate: 0.001
epochs_per_round: null
batches_per_round: 5
same_train_test_clients: True

# data
dataset: BEMNIST
dataset_fraction: 0.05
distribution_type: "niid"
batch_size: 10

# docs
results_dir_path: "./results/acc"
