# todo: describe the config
# training
num_rounds: 1_000
num_clients_per_round: 5
learning_rate: 0.001
epochs_per_round: 5
batches_per_round: null
same_train_test_clients: False

# data
dataset: FEMNIST
dataset_fraction: 0.05
distribution_type: "niid"
batch_size: 10

# docs
results_dir_path: "./results"
